Hipo/university-domains-list

world_universities_and_domains.json

List of universities in Azerbaijan updated with official website addresses and names. Closed universities removed from list.

List of universities in Azerbaijan

---

world_universities_and_domains.json

Önceden eklenmemiş yada yeni açılmış olan üniversitelerin hepsini ekledim. Kapatılan üniversitelerin hepsini çıkardım. Yani son şekli Türkiye'deki güncel üniversite listesi oldu.

Updated turkish universities 

---

world_universities_and_domains.json

Added 907 new schools based on http://www.usnews.com/education/community-colleges

added US community colleges

---

world_universities_and_domains.json

California State University, Sacramento

Remove duplicate entry

---

world_universities_and_domains.json

removing HTML special characters

---

world_universities_and_domains.json

Hello!
I've updated Universitas Klabat domain.
Ping to @yigitguler 
Thank you~

Update Universitas Klabat domain

---

world_universities_and_domains.json

Hi, Universitas Ibn Chaldun Jakarta have changed their website.

Update Universitas Ibn Chaldun Jakarta Website & Domain

---

world_universities_and_domains.json

Minor corrections to the names and domains of some Dutch universities.

Name and domain corrections for Dutch universities

---

world_universities_and_domains.json

* Made corrections in several Indian universities
* Ensured all [NITs](https://en.wikipedia.org/wiki/National_Institutes_of_Technology) are listed by adding/updating/sorting.

Add & update several Indian universities

---

world_universities_and_domains.json

Some of the domain where invalid as the port (from the website was in the domain name). This is fixed now.
Also adding one university: université de Lorraine

Cleaning up some domain and adding one french university

---

world_universities_and_domains.json

* Add AgroSup Dijon
* Delete Université de Bourgogne and Université de Franche-comté
* Add Université Bourgogne - Fanche-comté (fusion)

Add and update french universities and schools

---

world_universities_and_domains.json

Delete ENSBANA school (fusion into AgroSup Dijon)

Delete ENSBANA school

---

world_universities_and_domains.json

Added Kumaraguru College of Technology

Added Kumaraguru College of Technology

---

world_universities_and_domains.json

Added Monash University South Africa

Added Monash University South Africa

---

world_universities_and_domains.json

It was rebranded in 2014 https://en.wikipedia.org/wiki/ITMO_University

update ITMO name

---

world_universities_and_domains.json

It was rebranded in 2014 https://en.wikipedia.org/wiki/ITMO_University

add Academic University

---

world_universities_and_domains.json

Hi adding the famous tuition free school :)

Adding 42 Born2Code FR and US

---

world_universities_and_domains.json

Previously I did mistake and entire structure of JSON was broken, now I have validated JSON and everything is fine.
Validated via [https://jsonlint.com](url)

Added two more universities to the JSON file (no more errors now)

---

world_universities_and_domains.json

New includes:
up.ac.mz
unizambeze.ac.mz
unilurio.ac.mz

Addition of 3 more universities

---

world_universities_and_domains.json

New entry about Free university of Tbilsi

Add Free University of Tbilisi

---

world_universities_and_domains.json

Changed domains for HS Ulm and HS Neu-Ulm

Updated HS Ulm and HS Neu-Ulm

---

world_universities_and_domains.json

Pull request for following issues:
#85 #69 #64 
Additionally updated Fachhochschule Düsseldorf to Hochschule Düsseldorf

Fix #85, 69, #64, Update FH Düsseldorf

---

world_universities_and_domains.json

IPLeiria's domain was outdated. Added email subdomain as well.

updated IPLeiria

---

world_universities_and_domains.json

Hi.
I just added university domain, without modifying list.

Add Republic of Korea University

---

world_universities_and_domains.json

#106 
Updated the domain and website

fixed domain and url for University of Trieste

---

world_universities_and_domains.json

add multiple domains

---

world_universities_and_domains.json

#111 
added domain and webpage to Hacettepe University

added domain and webpage to Hacettepe University

---

world_universities_and_domains.json

I just added the new universities at the top of the file - hopefully that is alright.

Add new universities, combine a few duplicate entries, and other minor updates

---

world_universities_and_domains.json

Add a new University Indus University from India

Add a new University

---

world_universities_and_domains.json

Fix 2 broken webpages URLs. These cause errors when treated as URL in Swift, Objective-C, etc.

Fix 2 broken URLs

---

world_universities_and_domains.json

I ran into a school domain from Quebec which I noticed wasn't in the list of domains. This appears to be three schools operating under a single administration so I'm not sure if I've formatted this correctly. Let me know if you need any changes made before accepting the PR.

adds a school I ran into from Quebec

---

world_universities_and_domains.json

Adding new entry for https://www.rsm.nl/ It seems to be a part of Rotterdam Erasmus University, but it has it's own website & domain. Wasn't sure if you would prefer it to be a separate entry or to add the domain to the other uni.

Adding new entry for Rotterdam School of Management

---

world_universities_and_domains.json

Added a new University from India, "Dharamsinh Desai University"

Added a new University

---

world_universities_and_domains.json

Added 4 Universities From India.
- Pandit Deendayal Petroleum University
- Parul University
- Charotar University of Science and Technology
- Navrachana University

Added 4 Universities From India

---

world_universities_and_domains.json

Added DHBW Mannheim to List

---

world_universities_and_domains.json

As title says, added a few schools from French group IONIS Group

Added a few schools from French group IONIS Group

---

world_universities_and_domains.json

changed Iran and Taiwan's names a bit
and just for the sake of consistency, I also changed the turkish letter "İ" to "I" :))
Many thanks for your great work. Really appreciate it!! :+1: :+1:

modify countries & universities names

---

world_universities_and_domains.json

{
"web_pages": [
"http://www.th-brandenburg.de/"
],
"name": "Technische Hochschule Brandenburg",
"alpha_two_code": "DE",
"state-province": null,
"domains": [
"th-brandenburg.de"
],
"country": "Germany"
},

Add Technische Hochschule Brandenburg

---

world_universities_and_domains.json

Add Moscow University for Industry and Finance “Synergy” (https://en.wikipedia.org/wiki/Synergy_University)

Add Synergy University

---

world_universities_and_domains.json

Fixes #133 
update University of Linz

update-University of Linz

---

world_universities_and_domains.json

Fixes for #123, #145, #147, and added UMass Lowell.

Fixes for #123, #145, #147, and added UMass Lowell

---

world_universities_and_domains.json

{
"web_pages": [
"https://www.nibm.lk/""
],
"name": "National Institute of Business Management",
"alpha_two_code": "LK",
"state-province": null,
"domains": [
"nibm.lk"
],
"country": "Sri Lanka"
}

Add NIBM to university-domains-list

---

README.md
world_universities_and_domains.json

Added DUT MMI - Université Bordeaux Montaigne.

---

world_universities_and_domains.json

added "CIC - Canadian International College"

---

world_universities_and_domains.json

"Prince William Sound Community College" is now "Prince William Sound College"

updated Prince William Sound Community College

---

world_universities_and_domains.json

added Hanoi University of Science and Technology

---

world_universities_and_domains.json

Added new information for ISCTE-IUL, the new designation of our university.

Added new information for ISCTE

---

world_universities_and_domains.json

added Box Hill Institute

---

world_universities_and_domains.json

This is my university, i discovered it is not in the list

added one university in china

---

world_universities_and_domains.json

to “BIIT” and “BIMS” Universities

Added States info of TWO universities of Pakistan

---

tests/main.py

I changed raw access with key to `self.assertIn` calls, it is more idiomatic for `unittest`, and also clearer.

Refactored tests

---

world_universities_and_domains.json

Added `"state-province"` data for a lot of Pakistani Universities and removed some of those Universities that were fake or had fake or illegal campuses in Pakistan.
For more info you can visit [this link](http://www.hec.gov.pk/english/universities/Pages/AJK/Illegal-DAIs.aspx)

Added State info for some Pakistani Universities and removed fake Universities

---

world_universities_and_domains.json

Thanks for the API.
Just used it for a demo and naturally ended up searching for my alma-mater + colleges from my hometown. I saw marywood wasn't included to quickly added.

added marywood Univeristy

---

world_universities_and_domains.json

I did my best that I could to find and remove the duplicates, but please make a test that would check for duplication.....
What about the record for this one -> _http://www.csbsju.edu/_ check it out please !!
How I did all of this ...?
Well here is the code... _(I know its not efficient)_ 😉
```javascript
let a = 0;
data.forEach(item => {
for (let i = 0; i < data.length; i++) {
const element = data[i];
if(item === element){
continue;
}
if(element.web_pages.length >= 1 ) {
if(element.web_pages[0] === item.web_pages[0] ){
console.log("-------------------");
console.log(element.web_pages[0]);
console.log("-------------------");
a++;
}
}
if(element.domains.length >= 1 ){
if (element.domains[0] === item.domains[0]){
console.log("-------------------");
console.log(elements.domains[0]); …
```

Tried to tie up some lose ends (removed some duplication)

---

world_universities_and_domains.json

FIXED #190 😇

---

world_universities_and_domains.json

Hello,
This adds University of Arkansas - Fort Smith to the list as well as adding an updated domain to University of North Texas Health Science Center.

Add University of Arkansas - Fort Smith, domain to UNTHSC

---

world_universities_and_domains.json

- Add Mohawk College from Canada:
https://www.mohawkcollege.ca/
- Add Polk State College from US
https://www.polk.edu/
*note: My project relies on this list for student e-mail verification, so I may be submitting a few more PRs in the coming days/weeks. Thank you for the timely responses!

Add Mohawk College, Polk State College

---

world_universities_and_domains.json

- Fix Brescia University College's name and website
- Add new domain to Massasoit Community College
- Add Brescia University
- Add Rogers State University
- Add Neumann University
- Add Fanshawe College

Fix and add a bunch of colleges

---

world_universities_and_domains.json

This fixes Winona State University's website and domain.

Fix Winona State University

---

tests/main.py
tests/requirements.txt
world_universities_and_domains.json

This PR adds URL and domain validation.

Add validators to test

---

world_universities_and_domains.json

Add another valid domain to WLU

Add domain to WLU

---

world_universities_and_domains.json

Adds Ashford University
https://www.ashford.edu/

Add Ashford University (US)

---

world_universities_and_domains.json

Add McPherson College

---

world_universities_and_domains.json

Add ISU email

---

tests/main.py

Fixed encoding issue on windows

---

world_universities_and_domains.json

fixed issues #195 -  #196 - #197 - #208 - #215

fixed university names&domains from open issues

---

world_universities_and_domains.json

Added the VERN' University of Applied Sciences to the university domains list.

added Vern uni HR

---

world_universities_and_domains.json

Fixes Durham College's website and email

Fix Durham College

---

world_universities_and_domains.json

Added a missing university, Indian Institute of Technology, Gandhinagar.
~ From India

Added IITGN, India

---

world_universities_and_domains.json

www.defiance.edu in Ohio, United States

Add Defiance College

---

world_universities_and_domains.json

Update St Andrews web page and domain

Update St Andrews

---

world_universities_and_domains.json

Guangzhou College of South China University of Technology
Xihua University

add two new universities.

---

README.md
world_universities_and_domains.json

Update universities and schools of Grenoble (France)
Add CPE Lyon

Updating universities and schools of France

---

README.md
world_universities_and_domains.json

Also updated contributors list.
https://www.imt-atlantique.fr/

Added IMT Atlantique (France)

---

world_universities_and_domains.json

Added Academy of Art University, was missing.

Added Academy of Art University

---

world_universities_and_domains.json

I noticed that there are some duplication universities. I deleted them.

Deleted duplications

---

world_universities_and_domains.json

For reference, see http://africauniversities.org/south-africa/

Updated and added new data for South African universities

---

world_universities_and_domains.json

Added province for universities in Iran.
Fixed some names and websites.

Added province for universities in Iran and some name fixes

---

world_universities_and_domains.json

-Added Lenoir-Rhyne University

Added Lenoir-Rhyne University

---

world_universities_and_domains.json

This is my first commit to a GitHub community. If I did something wrong, I apologize and will try to fix it as soon as possible. Thanks!

Add provinces and update web pages to Universities in Thailand

---

world_universities_and_domains.json

Added Ontario Tech, Langara College, and Point Park University

Added Ontario Tech, Langara College, and Point Park University

---

world_universities_and_domains.json

Fixed some entries that contained IP addresses for domain and website with actual domains. 
This included one university that was closed in 2010, which I removed from the list.

Replaced IP addresses with actual domains

---

world_universities_and_domains.json

Added a new university data to world_universities_and_domains.json.

Added Madras Institute of Technology

---

world_universities_and_domains.json

Old domain took you nowhere, updated domains

Fixed UC Denver, domain was incorrect

---

world_universities_and_domains.json

Plus 
- updating some web pages URL's 
- and removing one duplicated college

adding states for Saudi Arabia's Universities 

---

world_universities_and_domains.json

https://en.wikipedia.org/wiki/Silesian_University_of_Technology

Add polsl.pl domain to existing Silesian University of Technology

---

world_universities_and_domains.json

https://id.wikipedia.org/wiki/Universitas_Duta_Bangsa
https://collegewikipedia.com/ranking-review/18743

Add Duta Bangsa University

---

world_universities_and_domains.json

Add ICFAI affiliated universities

---

world_universities_and_domains.json

https://en.wikipedia.org/wiki/University_of_Tyumen

New domain for Univerisy of Tyumen

---

world_universities_and_domains.json

https://nl.wikipedia.org/wiki/Odisee

Add University College Odisee

---

world_universities_and_domains.json

Northwood University did not previously exist in the json file.

Added Northwood University

---

world_universities_and_domains.json

Add Instituto Infnet to the list

Add Instituto Infnet

---

world_universities_and_domains.json

https://en.wikipedia.org/wiki/Metropolia_University_of_Applied_Sciences

Add Metropolia University of Applied Sciences

---

world_universities_and_domains.json

https://www.dhbw.de/english/home

Add all DHBW campuses

---

world_universities_and_domains.json

https://en.wikipedia.org/wiki/University_of_Pittsburgh_at_Bradford

Added University of Pittsburgh at Bradford

---

world_universities_and_domains.json

Hi all,
added a remote university in from Germany!

Add FOM college

---

world_universities_and_domains.json

* HBU
* ETBU
* USYD
* Brookings
* Johns Hopkins
* PFW
* UCOP
* UC Hastings
* Mayo

adds handful of institutions

---

world_universities_and_domains.json

- **Universitas Pembangunan Nasional "Veteran" East Java**
Renamed it into Universitas Pembangunan Nasional "Veteran" Jawa Timur (according to its website).
- **Universitas Madura**, moved to https://unira.ac.id
- **Universitas Tidar**, moved to https://untidar.ac.id
- Akademi Farmasi Mitra Sehat Mandiri Sidoarjo
- Universitas Maarif Hasyim Latif
- STIKES RS Anwar Medika
- Universitas Muhammadiyah Sidoarjo
- Universitas Trunojoyo Madura
- STIKES Bina Sehat PPNI Mojokerto
- Universitas PGRI Adi Buana Surabaya
- Universitas Pembangunan Nasional "Veteran" Jakarta
- Universitas Pembangunan Nasional "Veteran" Yogyakarta

Update University Data and Add New

---

world_universities_and_domains.json

Added more universities from my city

Added more universities from Pakistan

---

world_universities_and_domains.json

Adds [University of the Arts London](https://www.arts.ac.uk)

Add University of the Arts London

---

world_universities_and_domains.json

Added new universities to the list, including those from the disjointing of the University of Malawi.

Malawi universities

---

world_universities_and_domains.json

Added Technische Hochschule Mittelhessen in Germany

Added THM.de https://www.thm.de/site/

---

world_universities_and_domains.json

- add The Education University of Hong Kong
- update some university email domain
https://www.polyu.edu.hk/its/emc/email/
https://www.eduhk.hk/ocio/email-services-students
https://email.cityu.edu.hk/home/weblogon_o365um.htm

update hong kong university information

---

world_universities_and_domains.json

US universities additions and update

---

world_universities_and_domains.json

Updated websites and domains for three universities located in Brno, Czech republic
﻿

Updated Czech Brno's universities

---

world_universities_and_domains.json

Hi,
I have changed `http` url to `https` version and also updated the name of the university.

upol.cz metadata

---

world_universities_and_domains.json

- College of Southern Nevada
- Emory & Henry College
- Moscow Pedagogical State University
- Bath Spa University

New 4 institutions

---

world_universities_and_domains.json

Added:
* University of Colorado Anschutz Medical Campus
* Vistula University
* VIT Bhopal
* Université Mohammed Premier Oujda
Added additional domains for:
* University of Melbourne
* University of Wollongong
* Universiteit Antwerpen
* Nile University
* Université de Haute-Alsace
* Indian Institute of Technology, Delhi
* Maastricht University
* University of Sheffield
* Universidad de la República

Add universities and domains

---

.gitignore
world_universities_and_domains.json

Added:
* Macedonian Academy of Sciences and Arts
Added domain for:
* University of Missouri
* Technical University of Wroclaw
* Sciences Po

Adding a few more domains, unis

---

world_universities_and_domains.json

Prempeh college is a secondary/high  school This might sound tricky but here is a reference from the wikipedia page
https://en.wikipedia.org/wiki/Prempeh_College

Prempeh College is not a University/College

---

world_universities_and_domains.json

Reference to the wikipedia page https://en.wikipedia.org/wiki/Sunyani_Technical_University

added Sunyani Technical University

---

world_universities_and_domains.json

Added Universidade Franciscana of Brazil.

Add UFN, Brazil

---

world_universities_and_domains.json

Please add IIT Bhubaneswar to the university list

added university: IIT Bhubaneswar

---

world_universities_and_domains.json

Added the respective states to each Philippine University. All the state data is based on the location on the University's website.

added regional states to the Philippine Unis

---

world_universities_and_domains.json

Fix HTML entities

---

world_universities_and_domains.json

* CUNY colleges currently not on the list
* Morehouse
* Clark (Atlanta)

feat: add extra cuny colleges + 2 misc

---

world_universities_and_domains.json

Adds:
* Audencia - France
* Universidad de La Frontera - Chile

Add Audencia and Universidad de La Frontera

---

world_universities_and_domains.json

This was added by me in #428.
Sorry!

Remove duplicate Universidad de La Frontera

---

world_universities_and_domains.json

This PR adds the following universities:
- Base model
- Hogeschool Gent
- Universidad Internacional Jefferson
- St Mary's University
- American University of Rome
- Leeds Trinity University
- University of St. Augustine for Health Sciences
- California Institute of the Arts
- Des Moines University
- Utah Tech University
- East Coast College
- Midwestern University
- Illinois Wesleyan University
- Swansea University
- Universidad EIA
- Nova School of Business and Economics
- VIA University College
- Maryville College
- Nelson Marlborough Institute of Technology
- SRM University
- Rennes School of Business
- York St. John University
- Endicott College
- The University of Alabama
- Great Basin College
- Thomas More Hogeschool
- Einsteinmed
- Miami Dade College
- Cardiff and Vale College
- …

Add more universities

---

world_universities_and_domains.json

addition of mnsuet.edu.pk

---

world_universities_and_domains.json

1.Zenith Univrsity
2. Lancaster University
3.Ghana Baptist Univrsity
4.Kessebn college
5. Christ Apostolic University

feat: add 5 Private Universities in Ghana

---

world_universities_and_domains.json

I have tested and confirmed the url has been moved permantely.

Fixes issue #424

---

world_universities_and_domains.json

Added Lübeck Academy of Music: https://en.wikipedia.org/wiki/L%C3%BCbeck_Academy_of_Music

Add mh-luebeck.de

---

world_universities_and_domains.json

I updated details on two German universities.
Ostfalia:
- The website changed
- Added new domain
- University was renamed back in 2009
source: https://de.wikipedia.org/w/index.php?title=Ostfalia_Hochschule_f%C3%BCr_angewandte_Wissenschaften&oldid=222313524
TU Braunschweig:
- The website changed
- Added new domain
- Updated the name
source: https://de.wikipedia.org/w/index.php?title=Technische_Universit%C3%A4t_Braunschweig&oldid=230019935

Updated details of two German universities

---

world_universities_and_domains.json

Add state-province for American International School of Cape Town

Add state-province

---

world_universities_and_domains.json

Adds 4 more CUNY colleges and London Interdisciplinary School.

Add more CUNY colleges and LIS

---

world_universities_and_domains.json

Adds a large batch of universities/colleges that we've seen are missing.

Add a batch of missing universities

---

world_universities_and_domains.json

Update Erzincan University domain and name

fix: update erzincan university

---

world_universities_and_domains.json

[add alternate for Indian Institute of Science](https://github.com/Hipo/university-domains-list/commit/988ce34c6b03f05053bc0c658362e15f84f1c61e)

Iisc.ac.in

---

world_universities_and_domains.json

added frankfurt school of finance & management

added new university

---

world_universities_and_domains.json

Update State/Province for Universities in Australia and New Zealand

Update Australia and New Zealand Universities

---

world_universities_and_domains.json

- Add some new universities to the list
- Update 'Mercyhurst College' university name to 'Mercyhurst University'

Update universities file

---

world_universities_and_domains.json

Added some Singapore institutions. Changed existing ones to use https.
Source: <https://moe.gov.sg/post-secondary/overview>

Add Singapore institutions

---

world_universities_and_domains.json

Added IIT Sri Lanka domain: iit.ac.lk

Added IIT Sri Lanka domain

---

world_universities_and_domains.json

International Institute of Information Technology, Hyderabad

added IIIT Hyderabad to the list

---

world_universities_and_domains.json

Added Lingdong University of Science and Technology

---

world_universities_and_domains.json

Add Asia-Pacific International University

---

world_universities_and_domains.json

added some universities from Chennai, Tamil Nadu, India

Added some universities in Chennai, India

---

world_universities_and_domains.json

Update Ewha Womans University name
This pr solves issue #525.

Fix Ewha Womans University

---

world_universities_and_domains.json

- added 'https://' to various webpages
- update domains
- removed a duplicate uni

Added https for some webpages and update domains of some colleges

---

world_universities_and_domains.json

This pr solves issue #503 raised to update the domain of Université Libre de Bruxelles

updated Université Libre de Bruxelles

---

world_universities_and_domains.json

This will add the Kermanshah University of Technology domain and information.

feat: kut (Kermanshah University of Tech) added

---

world_universities_and_domains.json

- Gwynedd Mercy University
- Ulster University
- Indiana University - Bloomington
- Middlesex University - London
- Utah Valley University
- Hochschule Luzern
- The University of Texas at Rio Grande Valley
- The University of Texas at San Antonio
- University of New Hampshire
- University of the Fraser Valley
- The University of North Carolina at Greensboro
- St. Francis College
- Northumbria University
- Mercyhurst University
- Hunter College CUNY
- Aberystwyth University
- Universiteit Leiden
- Virginia Tech
- The University of Texas at Austin
- The University of Sheffield
- Newcastle University
- University of Illinois, Urbana-Champaign
- Unity Environmental College
- Ohio State University - Columbus
- The Chinese University of Hong Kong

Add and update some universities

---

world_universities_and_domains.json

Added a new University (Miva Open University, Nigeria)

Included a new University.

---

world_universities_and_domains.json

Changed some non relevant links in Belarus region, bcs some links doesn't work

changed non relevant links in Belarus

---

world_universities_and_domains.json

As best as I can tell this is a university in Mexico.

Add Universidad Guadalajara Lamar

---

world_universities_and_domains.json

Adding  "Shiga Prefecture Agricultural Technology Promotion Center".

Add Shiga Prefecture Agricultural Tech

---

world_universities_and_domains.json

https://www.canterbury.ac.nz/its/knowledge-base/email/

Add email domain for Canterbury

---

world_universities_and_domains.json

Adds student mail domain instead of only the faculty one.

Adds additional Sacred Heart domain for students

---

world_universities_and_domains.json

Adds the following universities:
Updates the following university name:

Add universities and update one

---

world_universities_and_domains.json

Adds Bay Path University

---

world_universities_and_domains.json

PR for adding COEP Technological Uni

Added COEP Technological University

---

world_universities_and_domains.json

I left the old domain even though it seems offline currently.

New domains for Ain Shams University

---

world_universities_and_domains.json

Add Greenville University

---

world_universities_and_domains.json

I've updated a university's metadata based on their new webpage

update university metadata

---

world_universities_and_domains.json

Four more Spain universities added:
- Universidad CEU Fernando III
- Universidad San Jorge
- Universidad de las Hespérides
- Universidad Europea del Atlántico

Add more Spain universities

---

world_universities_and_domains.json

Hi, I found some irregular hidden whitespace characters in the JSON file. Here is a PR to remove them.
more info: https://eslint.org/docs/latest/rules/no-irregular-whitespace

remove irregular whitespaces (U+200b)

---

world_universities_and_domains.json

Added a Pakistani University located in the Sindh Province

added PK university

---

world_universities_and_domains.json

Found some missing universities :)

Add more French universities

---

world_universities_and_domains.json

Add Osaka Electro-Communication University domain

---

world_universities_and_domains.json

Update info for JNTU/JNTUH
Update State, University name, domain and URL

Update info for JNTU/JNTUH

---

world_universities_and_domains.json

Add Ara.ac.nz

---

world_universities_and_domains.json

This table provides a list of college names along with their respective website addresses for quick reference.
| College Name                                       | Website Address                      |
|----------------------------------------------------|--------------------------------------|
| JIS University                                     | [jisuniversity.ac.in](https://www.jisuniversity.ac.in/)       |
| JIS College of Engineering                         | [jiscollege.ac.in](https://www.jiscollege.ac.in/)               |
| Narula Institute of Technology                     | [nit.ac.in](https://www.nit.ac.in/)                              |
| Guru Nanak Institute of Technology                 | [gnit.ac.in](https://gnit.ac.in/)                                |
| Guru Nanak …

Add Colleges

---

world_universities_and_domains.json

2 additions, 2 new domains, 1 removal

---

world_universities_and_domains.json

Add Toronto Baptist Seminary and Bible College

Add TBS College

---

world_universities_and_domains.json

I correct "Mangement" to "Management" and change all "Two spaces" to "One space" in name fiel

Fix typo and spaces

---

world_universities_and_domains.json

correcting names according to wikipedia and their own website

correct names

---

world_universities_and_domains.json

http://silpakorn.edu -> https://www.su.ac.th/th/index.php

fix: add additional domain for silpakorn university

---

world_universities_and_domains.json

This PR adds "Alvernia University.

Add 'Alvernia University'

---

world_universities_and_domains.json

add nusa putra university

---

world_universities_and_domains.json

This PR adds the following universities:
- University of Pikeville
- University of Holy Cross
- Hellenic American University
- Uniwersytet SWPS
- Turība University
- MIT World Peace University
- Manav Rachna University
- Shanghai Jiao Tong University

Update universities list

---

world_universities_and_domains.json

Add Engineering Institute of Technology
https://www.eit.edu.au/about-eit/

Add Engineering Institute of Technology

---

world_universities_and_domains.json

Added school "Okinawa Institute of Science and Technology" Graduate University.

Added "Okinawa Institute of Science and Technology"

---

world_universities_and_domains.json

We'd like to add the Institute for Advanced Study in Princeton, NJ.
Thanks,
Brian

Add IAS.edu

---

world_universities_and_domains.json

The previously used domain redirects to the new one.

Fix WHU domain and name

---

world_universities_and_domains.json

Fixed the state names for india countries list for 2 univerisities

Fixed the state names for india countries list for 2 univerisities

---

world_universities_and_domains.json

This PR changes some typos on universities

technicial names

---

world_universities_and_domains.json

Resolves #694 
This PR adds [Purdue Global University](https://www.purdueglobal.edu/) the list

Add Purdue Global University to the list

---

world_universities_and_domains.json

Adds a batch of Brazilian Universities

chore: add batch of brazilian universities

---

world_universities_and_domains.json

Added Ventspils University of Applied Sciences. Link to university : https://www.venta.lv/

Added Ventspils University of Applied Sciences

---

world_universities_and_domains.json

Adds [Université de Toulouse-le-Mirail (Toulouse III)](http://www.univ-tlse3.fr/) to the university list.

Add Université de Toulouse-le-Mirail (Toulouse III)

---

LICENSE.txt

Closes issue https://github.com/Hipo/university-domains-list/issues/689

Update license date

---

tests/test_trimming.py
world_universities_and_domains.json

Add test for trimming
Example: https://github.com/Hipo/university-domains-list/pull/118
Related issue: https://github.com/Hipo/university-domains-list/issues/119

Add trim test and delete extra spaces

---

world_universities_and_domains.json

Merge Université de Montpellier I and Université de Montpellier II

---

world_universities_and_domains.json

Fix Instituto Universitario CEMA domain

---

world_universities_and_domains.json

Update University of Milan web_pages

---

world_universities_and_domains.json

Fix Universidad de Palermo domain

---

world_universities_and_domains.json

Add Central Supélec

---

world_universities_and_domains.json

"Fachhochschule Augsburg" renamed

---

world_universities_and_domains.json

Add COER University Roorkee

---

README.md
world_universities_and_domains.json

Change Turkey To Turkiye
