world_universities_and_domains.json
The old handle "tu-muenchen.de" is still working, but the new domain name "tum.de" is used for university email adresses and is the newer one. Thus we should switch to "tum.de"
=> Update Technische Universität München with correct domain name

world_universities_and_domains.json
Generally, all students’ email addresses use the lmu.de domain e.g.
sven.svenson@campus.lmu.de
=> Adding further domain for Ludwig-Maximilians-Universität München

world_universities_and_domains.json
They renamed from Fachhochschule Deggendorf to Technische Hochschule
Deggendorf couple of years ago.
=> domain of Fachhochschule Deggendorf has changed

world_universities_and_domains.json
I just had a user of our project website try to use his student e-mail address to download something, which didn't work, because apparently his university (University of Roma "Tor Vergata", http://uniroma2.it/) uses a different domain for student e-mail accounts than they do for the website: `first.last@students.uniroma2.eu`. It looks half dodgy at first glance because that URL serves only a placeholder CMS website, but I did find a reference from uniroma2.it that uses the .eu domain [here](https://translate.google.nl/translate?hl=en&sl=it&u=http://docs.ccd.uniroma2.it/pmwiki.php/Main/Office365&prev=search), so I guess it's legit. I also don't see why someone would try to spoof an e-mail address like this to download our project, I believe it's the first download in a year or something …
=> Differing e-mail/http domain names

world_universities_and_domains.json
#35 
correct a typo in a university name .
=> Issue #35 - typo in `Mehmet Akif Ersoy University` name

world_universities_and_domains.json
"Institut Teknologi Telkom" is an old name for new "Universitas Telkom"
http://www.stttelkom.ac.id is no longer available since it moving to http://www.telkomuniversity.ac.id
=> Edit Universitas Telkom data

world_universities_and_domains.json
The former domain of usyd.edu.au is valid but is not the domain that is actively being used by members of the university, most notably in their emails. Contact all comes from sydney.edu.au. Until multiple domains per institution is possible I think sydney.edu.au is more correct for University of Sydney.
=> Correcting University of Sydney to their published domain

world_universities_and_domains.json
The original entry contains empty **domain** member and excessive slashes in the **web_page** member
The fixed entry contains the correct **domain** member [szu.sk](http://www.szu.sk/) and correct **web_page** member [http://www.szu.sk/](http://www.szu.sk/)
=> Fix Slovak Medical University entry domain and web_page

world_universities_and_domains.json
According to official website https://www.pw.edu.pl/engpw proper name in english is "Warsaw University of Technology"
=> pw.edu.pl name update

README.md, world_universities_and_domains.json
See the commit history for more details on these changes.
Also, I wrote a script that can alphabetize the entries - if you think there is any value in having them in order (first by country code, with US first, and then by domain name) I can run the script and issue another pull request with the results (it will be a noisy commit, though.)  Just let me know!
Also, I've found that there are several K-12 schools that have .edu addresses - should we add entries for those?  Or try to keep this list geared more toward higher education?
=> Adding several more universities to the list and updating some existing entries

world_universities_and_domains.json
Stony Brook University has an academic medical centre with a seperate domain & website [stonybrookmedicine.edu](https://stonybrookmedicine.edu/) that they seem to be putting at least part of the medical cohorts email addresses under.
=> add stonybrookmedicine

world_universities_and_domains.json
Updated correct domains for Seneca & Sheridan Colleges in Ontario, Canada
=> Updated Ontario Canada schools

world_universities_and_domains.json
- Added 2 universities: Pham Ngoc Thach University of Medicine (http://www.pnt.edu.vn/) and Vietnamese - German University (http://vgu.edu.vn/)
- Corrected spelling of "Thainguyen University of Agriculture and Forestry" (http://tuaf.edu.vn/en-Us)
=> update certain universities in Vietnam

world_universities_and_domains.json
The University of Aberdeen has two domain names - one for staff and services and one for students. The one for students was missing from your list.
=> Added the second domain of the University of Aberdeen.

world_universities_and_domains.json
http://gleanernow.com/news/2006/11/walla-walla-college-change-name
=> Walla Walla College was renamed Walla Walla University and its domain has changed

world_universities_and_domains.json
Calmar is only one of NICC's two campuses. I propose removing the `-Calmar` suffix from the NICC entry.
=> Remove Calmar suffix from Northeast Iowa Community College

world_universities_and_domains.json
Manchester Business School is part of the University of Manchester but uses its own domain for web and email.
University of Manchester deprecated man.ac.uk a long time ago, now uses manchester.ac.uk
=> University of Manchester canonical domain is manchester.ac.uk, plus mbs.ac.uk

world_universities_and_domains.json
This short url is also used for students email adresses.
=> Add university of muenster short url

world_universities_and_domains.json
[...] the foundation of Forschungszentrum Karlsruhe and [...] the foundation of Universität Karlsruhe [...]  merge into the new legal entity of KIT [...] on October 01, 2009.
Source: [http://www.kit.edu/kit/english/history.php](http://www.kit.edu/kit/english/history.php)
=> Uni Karlsruhe -> Karlsruhe Institute of Technology (KIT)

world_universities_and_domains.json
Adds nsbm
{
"web_pages": [
"http://www.nsbm.lk/"
],
"name": "National School of Business Management",
"alpha_two_code": "LK",
"state-province": null,
"domains": [
"nsbm.lk"
],
"country": "Sri Lanka"
}
=> Adds nibm to list

world_universities_and_domains.json
Newly added institutions:
- Lambton College (CA)
- Hochschule Hannover (DE)
Note: Originally added institutions in alphabetical order, hence the disparity on the location of additions in the commits.
=> Added Lambton College, Hochschule Hannover.

world_universities_and_domains.json
I messed up on my last pull request because I deleted my fork and couldn't find a way to update it...sorry for the inconvenience.
I fixed what you told me to (adding `btu.ge` to domains list).
[Here](https://btu.ge/en/about-us/authorization--accreditation "Official notice.") is the accreditation information again, just in case.
=> Added Business and Technology University

world_universities_and_domains.json
Domain `mines-ales.org` is used for students' addresses (source: https://www.mines-ales.fr/reseau/e-mail-eleves/index.html).
=> Update: added domains + webpage for École des Mines d'Alès (FR)

world_universities_and_domains.json
The name and the domain of the university of Dortmund were outdated.
=> Fix name and domain of TU Dortmund

world_universities_and_domains.json
ohiou.edu domain has been decommissioned and now redirects to ohio.edu. Remove outdated duplicate entry
https://www.ohio.edu/oit/web/websites/custom-web-addresses/decommissioned
=> Remove duplicate Ohio U entry with old domain

world_universities_and_domains.json
This fixes MRU's website, name, and domain. I'm unsure if I should have kept the old domain, but all MRU emails now end in @mtroyal.ca instead of @mtroyal.ab.ca.
=> Fix Mount Royal University

world_universities_and_domains.json
The university is now known as just Queen Mary, University of London. They also now use the domain name `qmul.ac.uk`, but they have kept the old domain too.
=> Fixed Queen Mary, University of London

world_universities_and_domains.json
An entry for METU already exists, starting at line 98541. Also it is the correct one, so we can remove this.
=> Remove duplicate METU

world_universities_and_domains.json
Added Aberdeen University student email domain name. The original one is staff-only
=> University of Aberdeen

world_universities_and_domains.json
"Fachhochschule für Technik und Wirtschaft Berlin" has gone through a rebranding to "Hochschule für Technik und Wirtschaft Berlin" a few years ago. Due to this, the domain changed to "htw-berlin.de". The old domain still receives emails so I kept it in the list.
=> Update HTW domain

world_universities_and_domains.json
The official name of the university is the Lomonosov Moscow State University (https://msu.ru/en). Also several years ago the main site switched to https protocol.
=> update for the Lomonosov Moscow State Univeristy and IBCH RAS

world_universities_and_domains.json
Ural State Technical University was renamed to Ural Federal University in 2010: https://urfu.ru/en/about-the-university/history/2000-10/
=> Replace USTU with URFU

world_universities_and_domains.json
student.aau.dk
uni.sydney.edu.au
student.lamk.fi
student.scad.edu
student.uts.edu.au
network.rca.ac.uk
aalto.fi
student.lut.fi
student.lboro.ac.uk
campus.ul.pt
fa.cvut.cz 
student.tudelft.nl
student.murdoch.edu.au
student.gsa.ac.uk
gapps.ntust.edu.tw
student.hs-anhalt.de
=> Added 16 missing domains and/or institutes

world_universities_and_domains.json
The domain for Islamic Azad University, Qazvin was wrong.
Corrected.
=> changed web_pages and domains for Islamic Azad University, Qazvin

world_universities_and_domains.json
Wirtschaftsuniversität Wien (Vienna Univ. of Econ. and Business) has the domain wu.ac.at. See: https://www.wu.ac.at/en/
=> added WU domain to Vienna Univ of Econ and Business

world_universities_and_domains.json
Nanjing University of Information Science and Technology
Originally called Nanjing Institute of Meteorology (until 2004)
=> Added Nanjing University of Information Science and Technology, Nanjing, China.

world_universities_and_domains.json
Update info of imperial college
=> Imperial college now uses imperial.ac.uk instead of ic.ac.uk

world_universities_and_domains.json
Not sure the domain changed or always was `uc.cl`, but `puc.cl` isn't correct.
=> Fix domain and website for uc.cl

world_universities_and_domains.json
According to student, the `g.` subdomain is used for active student emails.
=> Student emails use g subdomain for nsu.ru

world_universities_and_domains.json
I left the old domain in list, it currently redirects to the new domain. The `uted.` subdomain is used for student emails.
=> new domain for Paris-EST

world_universities_and_domains.json
- add "mytum.de" to valid domains according to https://www.it.tum.de/en/it/faq/it-services/e-mail/e-mail-in-general/how-can-i-create-a-tum-e-mail-address-how-can-i-access-my-e-mails/
=> Add Student email domain for TU Munich

world_universities_and_domains.json
Adds [Futureworks](https://futureworks.ac.uk/), a university in Manchester, UK
=> Add Futureworks

world_universities_and_domains.json
Universite Pierre et Marie Curie has changed name to Sorbonne Université - Faculté des sciences after a merger.
Old registered website and domain "jussieu.fr" aren't used for accounts anymore.
Added the domains used for Université Pierre et Marie Curie and added the new domains for Sorbonne Université both are active for now.
=> Change Universite Pierre et Marie Curie to new name. Added all domains

world_universities_and_domains.json
- Added state provinces to all South African provinces. 
- And fixed one typo where the Province name was on the actual varsity name.
=> Added 'State-Province' to all South African universities

world_universities_and_domains.json
The Information Technology University of Pakistan wasn't there in the list of universities and so I have added it with complete information including the province/state. The university was established in 2012 is quite well-known but for some reason, wasn't there.
=> Added ITU of Pakistan

world_universities_and_domains.json
University of Macau changed its domain in 2020.
Please accept my pull request.
=> Change domain for University of Macau

world_universities_and_domains.json
This is the merger of Aix-Marseille I-III.
See https://en.wikipedia.org/wiki/Aix-Marseille_University#Recent_history_(1968%E2%80%93present), it seems the domains of the other universities are kept around (at least for some departments)
=> Add Aix-Marseille University.

world_universities_and_domains.json
You may notice that https://www.vub.ac.be redirects now to https://www.vub.be, and that `@vub.be` is now the preferred email domain for staff, personnel and students.
=> Add vub.be as VUB domain

world_universities_and_domains.json
I live in Ghana and Ghana has changed some of  its polytechnnics to Technical universities. If you want to test the validity you can try loging  onto the changed domains. You will see it is not working no more.
=> changed Ghana Polytechnics to Technical University

world_universities_and_domains.json
Adding libresoft.es and gsyc.es. Both are Universidad Rey Juan Carlos research groups
Signed-off-by: Pablo Hinojosa <phinojosa@bitergia.com>
=> Add URJC research groups

README.md
To avoid listing more than 100 contributors I add a link to the GitHub contributors list
=> Add link to more contributors

world_universities_and_domains.json
There are currently two entries for the University of Zurich:
* One with the domain [unizh.ch]. This entry exists since the very first commit. This domain belongs to the same university. In fact [unizh.ch] redirects to [uzh.ch].
* One with the domain [uzh.ch]. This entry was added in #72 
I chose to keep the version without umlaut (Zurich instead of Zürich) since that's the spelling the university uses on the [English version of their website](https://www.uzh.ch/en.html).
[unizh.ch]: http://www.unizh.ch
[uzh.ch]: https://uzh.ch
=> University of Zurich

world_universities_and_domains.json
“Fachhoschule Köln” changed its name to “Technische Hochschule Köln”.
I updated the name, domain, and webpage to the correct values (fh-koeln.de still works, but reroutes to th-koeln.de).
Source: Just graduated from this university.
=> Updated Fachhoschule Köln

world_universities_and_domains.json
I was not able to find the website for `National Technological University` in the US and the webpage: `http://www.ntu.edu/` does not exist.
=> fix: Remove institution that does not exist

world_universities_and_domains.json
Adjusting official naming for:
- HEC
- Hochschule Mittweida
- Universität Zürich
- Universität St. Gallen (HSG)
Adding additional domains for Hochschule Mittweida
Adding:
- CLSBE
- EADA
- IMD
- INSEAD
- HFF
=> Adjusting official naming, adding new universities

world_universities_and_domains.json
Add to the list of universities all the Australia TAFE (Training and Further Education) universities nationwide. These are vocational universities, offering diplomas and associates degrees primarily, but they are very much universities.
=> Add Australian TAFE Universities

.travis.yml, tests/test_domains.py, world_universities_and_domains.json
- test for webpages
- validation for webpages
- added error msg for tests
- cleaned up the json_list
- added datatype validation
=> Changes to CI tests

world_universities_and_domains.json
- Removes trailing whitespace from one entry
- Adds student.unisg.ch which is used for student email addresses in Universität St. Gallen (HSG).
=> Add student.unisg.ch to Universität St. Gallen (HSG)

world_universities_and_domains.json
The "Quaid e Awam University of Engineering, Sciences & Technology" university previously had the domain "panasia.org.sg". DDG[^1] and wikipedia[^2] both agree that the domain name is quest.edu.pk.
From the QUEST webpage clicking "E-mail" redirects to a google email login for the domain quest.edu.pk. So that's the email domain too.
As for removing `panasia.org.sg`, loading that domain shows a "Account Suspended" page.
[^1]: https://duckduckgo.com/?q=Qauid-e-Awam+University+of+Engineering+Sciences+%26+Technology
[^2]: https://en.wikipedia.org/wiki/Quaid-e-Awam_University_of_Engineering,_Science_%26_Technology
=> Fix the domain for Pakistan/QUEST

world_universities_and_domains.json
Adds esmad.ipp.pt and www.esmad.ipp.pt, two domains for the Escola Superior de Media Artes e Design in Portugal.
=> Add Escola Superior de Media Artes e Design (esmad.ipp.pt)

world_universities_and_domains.json
Change web page and domain for Delaware State University from
-  http://www.dsc.edu/ -> https://www.desu.edu/ 
- dsc.edu -> desu.edu
A simple website check will reveal that the previous web page is incorrect.
=> Change web page and domain for Delaware State University

world_universities_and_domains.json
- Removed defunct and merged Technological Educational Institutes (they ceased to exist as per the Greek Government Gazette A 1933/17-03-2019 (https://www.et.gr/api/DownloadFeksApi/?fek_pdf=20190100070)
- Updated the websites of private institutions
- Removed records of private institutions that seemed to be defunct
- Removed University of Central Greece as it was declared defunct by the Greek Government back in 2013
- Updated the domains of the International Hellenic University (IHU) and Hellenic Army Academy, as they acquired new ones.
- Added A.S.PAI.TE.
- Added regions to most universities, with Hellenic Open University as an exception, since it has branches all over Greece and its lessons are primarily held online
- Added https to links
=> Updated universities in Greece

world_universities_and_domains.json
- The old `iticu.edu.tr` domain is outdated, changed it to `ticaret.edu.tr`
- Also add student email domain `istanbulticaret.edu.tr`
=> Update the Istanbul Ticaret University - TR

world_universities_and_domains.json
For the consistency between this project and the pycountry ISO databases, revert to Taiwan's name to "Taiwan, Province of China".
Refer to [1] for more details.
[1] https://github.com/pycountry/pycountry/blob/main/src/pycountry/databases/iso3166-1.json
=> Fix the name of Taiwan

world_universities_and_domains.json
- Removing Hall County Schools and Berufliche Schulen Altötting which are high schools/vocational schools.
- This undoes the PRs (https://github.com/Hipo/university-domains-list/pull/547 & https://github.com/Hipo/university-domains-list/pull/548 )
- This issue is also referenced here: https://github.com/Hipo/university-domains-list/issues/550
=> Remove high school and vocational school

world_universities_and_domains.json
* Updated university names (e.g., adding missing "The").
* Removed "Hong Kong Institute of Education" as it was renamed to "The Education University of Hong Kong" since 2015.
* Updated "Open University of Hong Kong" with its new name "Hong Kong Metropolitan University" and domain.
* Renamed "Hong Kong Shue Yan College" to "Hong Kong Shue Yan University".
* Updated web page URLs (mainly changed http to https).
* Added students/alumni/retirees domains.
=> Updated universities in Hong Kong

world_universities_and_domains.json
As a result of merger of "National Chiao Tung University" and "National Yang-Ming University":
* Removed "National Chiao Tung University".
* Removed "National Yang Ming Medical College" (predecessor of "National Yang-Ming University").
* Added "National Yang Ming Chiao Tung University".
=> Updated universities in Taiwan

world_universities_and_domains.json
Removes duplicate entry for Ulster University under their old name (University of Ulster) and adds the ulst.ac.uk domain to Ulster University. The web page hasn't been added to the array as it's no longer live on that domain.
=> remove duplicate ulster entry

world_universities_and_domains.json
I set the state/province value to "Istanbul". Normally, the name Istanbul is called `İstanbul` in the Turkish alphabet, but I wrote it with `I` for compatibility.
=> Update state/province of Istanbul Ticaret University

world_universities_and_domains.json
Added a new domain for Illinois Institute of Technology. Used to go there and this is the new student domain listing.
=> Added a new domain for IIT

world_universities_and_domains.json
I searched google and duckduckgo, they all give same suggestion, and the domain doesn't exist either
=> University Polsdam doesn't exist, probably mistaken by University Potsdam

world_universities_and_domains.json
Renamed National University of Ireland, Galway after the recent rebrand of the college along with its new domain name.
New domain:
https://www.universityofgalway.ie/
Source: 
https://www.rte.ie/news/connacht/2022/0427/1294705-nui-galway-name/
=> Updated data entry for University Of Galway

filter.py
The PR takes care of intervention for this [issue](https://github.com/Hipo/university-domains-list/issues/666) as part of an experiment.
The experiment is detailed [here](https://github.com/evidencebp/pylint-intervention)
Code uses the pattern
if test:
return True
else:
return False
Pylint alerts on that and suggest a simplification: The if statement can be replaced with 'return bool(test)' (simplifiable-if-statement)
Hence I removed the if and instead returned the test directly.
That simplifies the code and makes it easier to understand.
=> Pylint alerts corrections as part of intervention experiment

world_universities_and_domains.json
Update Ecole Normale Supérieure de Cachan name and domail list based on:
- https://ens-paris-saclay.fr/en/school/history-school
- https://en.wikipedia.org/wiki/%C3%89cole_normale_sup%C3%A9rieure_Paris-Saclay
=> Update Ecole Normale Supérieure de Cachan name and domain list

world_universities_and_domains.json
I've corrected the spelling of some belarusian university names.
Removed the redundant `s` from the word `Belarusian`.
Spelling could be checked in wikipedia https://en.wikipedia.org/wiki/List_of_universities_in_Belarus or in English versions of university pages (for example https://bsu.by/en/).
=> Fix belarusian universities' names

world_universities_and_domains.json
`uwi.tt` redirects to `sta.uwi.edu`, and students use email subdomain `my.sta.uwi.edu`.
=> sta.uwi.edu

world_universities_and_domains.json
Pukyong National University have mail domain for students: `pukyong.ac.kr`.
https://mail.pukyong.ac.kr:8443/main/main.jsp
=> Add domain for Pukyong National University: pukyong.ac.kr 

world_universities_and_domains.json
Currently the name "Universidad Distral " appears, but it should be "Universidad Distrital"
=> fix: name for Universidad Distrital in Colombia

world_universities_and_domains.json
NSIT WAS RENAMED TO NSUT AS PER
"Delhi Netaji Subhas University of Technology Act, 2017 (DELHI ACT 06 of 2018)"
=> updated nsit to nsut as per govt of nct of delhi 

world_universities_and_domains.json
The name for the University "Universitat Ramon Llull" does not actually have an accent in the word "Ramon" as seen in the official site: https://www.url.edu/.
Regards,  
Iscle
=> (fix) Fixed typo for Universitat Ramon Llull

world_universities_and_domains.json
- Set 'state-province' to 'Gujarat' for Nirma University and Pandit Deendayal Energy University.
- Updated Pandit Deendayal's name, domains, and web pages to reflect its current status. It is now "Pandit Deendayal Energy University". the http://www.pdpu.ac.in/ webpage just redirects you now to http://www.pdeu.ac.in/ . I kept both since that does still work.
=> Update university data for a couple of institutions

world_universities_and_domains.json
Added Minerva University, based in San Francisco.
Official Website: https://www.minerva.edu/
Wikipedia Page: https://en.wikipedia.org/wiki/Minerva_University
=> Added Minerva University
